(define (any? pred? xs)
 (and (not (null? xs)) (or (pred? (car xs)) (any? pred? (cdr xs)))))
(any? odd? '(1 3 5 7) )
(any? odd? '(0 2 4 6) )
(any? odd? '() )
(define (all? pred? xs)
 (and (not(null? xs)) (and (pred? (car xs) ) (any? pred? (cdr xs)))))
(all? odd? '(1 3 5 7))
(all? odd? '(0 1 2 3))
(all? odd? '(0 2 4 6))
(all? odd? '())
