(load "Utest.rkt")
(load "dereviate.rkt")


(define the-tests
  (list (test (derivative '(2)) '(0))
        (test (derivative '(x)) '(1))
        (test (derivative '(- x)) '(-1))
        (test (derivative '(* 1 x)) '(* 1 1))
        (test (derivative '(* -1 x)) '(* -1 1))
        (test (derivative '(* -4 x)) '(* -4 1))
        (test (derivative '(* 10 x)) '(* 10 1))
        (test (derivative '(- (* 2 x) 3)) '(- (* 2 1) 0))
        (test (derivative '(expt x 10)) '(* 10 (expt x 9)))
        (test (derivative '(* 2 (expt x 5))) '(* 2 (* 5 (expt x 4))))
        (test (derivative '(expt x -2)) '(* -2 (expt x -3)))
        (test (derivative '(expt 5 x)) '(* (log 5) (expt 5 x)))
        (test (derivative '(cos x)) '(- (sin x)))
        (test (derivative '(sin x)) '(cos x))
        (test (derivative '(expt (exp 1) x)) '(* (log (exp 1)) (expt (exp 1) x)))
        (test (derivative '(* 2 (expt (exp 1) x))) '(* 2 (* (log (exp 1)) (expt (exp 1) x))))
        (test (derivative '(* 2 (expt (exp 1) (* 2 x))))
              '(* 2 (* (* (log (exp 1)) (expt (exp 1) (* 2 x))) 2)))
        (test (derivative '(log x)) '(/ 1 x))
        (test (derivative '(* 3 (log x))) '(* 3 (/ 1 x)))
        (test (derivative '(+ (expt x 3) (expt x 2)))
              '(+ (* 3 (expt x 2)) (* 2 (expt x 1))))
        (test (derivative '(+ (* 2 (expt x 3)) (* 2 (expt x 2))))
              '(+ (* 2 (* 3 (expt x 2))) (* 2 (* 2 (expt x 1)))))
        (test (derivative '(/ 3 x)) '(* -3 (/ 1 (expt x 2))))
        (test (derivative '(/ 3 (* 2 (expt x 2))))
              '(/ -6 (* 2 (expt x 3))))
        (test (derivative '(* 2 (* (sin x) (cos x))))
              '(* 2 (+ (* (cos x) (cos x)) (* (- (sin x)) (sin x)))))
        (test (derivative '(* 2 (* (expt (exp 1) x) (* (sin x) (cos x)))))
              '(* 2 (+ (* (* (log (exp 1)) (expt (exp 1) x)) (* (sin x) (cos x)))
                       (* (+ (* (cos x) (cos x)) (* (- (sin x)) (sin x))) (expt (exp 1) x)))))
        (test (derivative '(sin (* 2 x))) '(* (cos (* 2 x)) 2))
        (test (derivative '(cos (* 2 (expt x 2))))
              '(* (- (sin (* 2 (expt x 2)))) (* 2 (* 2 (expt x 1)))))
        (test (derivative '(sin (log (expt x 2))))
              '(* (cos (log (expt x 2))) (* (/ 1 (expt x 2)) (* 2 (expt x 1)))))
        (test (derivative '(+ (sin (* 2 x)) (cos (* 2 (expt x 2)))))
              '(+ (* (cos (* 2 x)) 2) (* (- (sin (* 2 (expt x 2)))) (* 2 (* 2 (expt x 1))))))
        (test (derivative '(* (sin (* 2 x)) (cos (* 2 (expt x 2)))))
              '(+ (* (* (cos (* 2 x)) 2) (cos (* 2 (expt x 2))))
                  (* (* (- (sin (* 2 (expt x 2)))) (* 2 (* 2 (expt x 1)))) (sin (* 2 x)))))))

(run-tests the-tests)