(define (interspers word list)
  (define (i2 word list ans)
    (if (null? list)
        (reverse ans)
        (if (null? (cdr list))
            (i2 word (cdr list) (cons (car list) ans))
            (i2 word (cdr list) (cons word (cons (car list) ans))))))
  (i2 word list '()))

(interspers 'x '(1 2 3 4))
(interspers 'x '(1 2))
(interspers 'x '(1))
(interspers 'x '())
(interspers '6 '(1 2 3 4))