(define (my-flatten . t) 
  (define (check xs ans) 
    (if (null? xs) 
        ans 
        (if (list? (car xs)) 
            (f2 ans '()) 
            (check (cdr xs) ans) )  )  ) 
  (define (f2 xs ans) 
    (if (null? xs) 
        (check ans ans) 
        (if (list? (car xs)) 
            (f2 (cdr xs) (append ans (car xs) ) ) 
            (f2 (cdr xs) (append ans (list (car xs) ) ) )  ) ) ) 
  (f2 (car t) '() ) )
(my-flatten '((1) 2 (3 (4 5)) 6))